### ISSUE TITLE
Support renaming a branch

### ISSUE THREAD

**Issue by tenfourzero** [thomasrepnik/idea-commit-prefix-plugin#16]
Great plugin, thanks to the dev :+1:

An observation that renaming a branch within the IDE (or from the cli) doesn't update the commit prefix. Hopefully this is an event you can hook into!

Thanks.

**Comment by thomasrepnik** [comment]
Thank you for your feature request. Glad you like the plugin!
I already found the corresponding event. Will release a new version soon, supporting this feature.

**Comment by thomasrepnik** [comment]
Renaming doesn't seem to work yet. Need to look at it again. 
The new release supports branch switches from cli/terminal only and will be released in the next days.

**Comment by thomasrepnik** [comment]
The fix was easy. Expect to have an updated version available in the next days. Enjoy

**Comment by tenfourzero** [comment]
Wonderful, already pulled and in use. Fantastic support of the plugin, thank you!!
