### ISSUE TITLE
After updating plugin to version 1.2.1 added commit prefix is not commited

### ISSUE THREAD

**Issue by skipor** [thomasrepnik/idea-commit-prefix-plugin#19]
### Affected Application:
IntelliJ IDEA 2022.2.3

### Describe the bug

After updating plugin to version 1.2.1, added commit prefix is not commited.

### To Reproduce

1. Do some changes in branch `feature/XXXXX-9999/description`
2. Commit with message `test`

**Expected behavior**
- Commit message is `XXXXX-9999: test` both in git log and commit dialog

**Actual behavior**
- Commit message is `test` in git log and `XXXXX-9999: test` in commit dialog

### Screenshots
<img width="1143" alt="Screenshot 2022-10-28 at 14 58 21" src="https://user-images.githubusercontent.com/4019825/198572605-38f2f4a0-9d64-4a74-b8ed-7f175581bf38.png">

### Additional context

Workaround - download [previous version 1.1.2](https://plugins.jetbrains.com/plugin/download?rel=true&updateId=140589) from [plugin versions page](https://plugins.jetbrains.com/plugin/14238-git-auto-prefix/versions) and install it from Disk.

**Comment by thomasrepnik** [comment]
Hi, thank you for using my plugin and reporting the issue.  

I just tried to reproduce the issue based on your description (with Intellij 2022.2.3), but i was not able to. 
Maybe i am doing something wrong....

1. I checked out a branch with a jira compatible branch name
2. I then deleted the whole commit message and added a message **without a prefix**
3. I then pressed the commit button
4. The results were
- The prefix got added to the commit message editor
- The message in the git history was commited with the prefix.

Here you have two screenshots
Right before pressing the commit button 
<img width="1091" alt="Bildschirmfoto 2022-10-28 um 17 51 41" src="https://user-images.githubusercontent.com/47736416/198681297-8d4723a2-2134-4e8e-bb47-17e24abd2526.png">

And after i pressed the commit button:
<img width="1095" alt="Bildschirmfoto 2022-10-28 um 17 53 06" src="https://user-images.githubusercontent.com/47736416/198681384-7caf4c92-f964-44c6-b824-8dc874a30bca.png">

Please let me now what i am missing here. Would appreciate to help you.

**Comment by thomasrepnik** [comment]
This issue was closed because of missing feedback.
