### ISSUE TITLE
Editable Template?

### ISSUE THREAD

**Issue by wdcossey** [thomasrepnik/idea-commit-prefix-plugin#2]
Need an option to edit the template.

Our JIRA tracking needs `ABC : 1234` with spaces either side of the `:`,

**Comment by thomasrepnik** [comment]
I will take a look 👍

**Comment by thomasrepnik** [comment]
Feature is available in [Version 1.0.3](https://plugins.jetbrains.com/plugin/14238-git-auto-prefix/versions)
