### ISSUE TITLE
Plugin stopped to work with new IntelliJ

### ISSUE THREAD

**Issue by Nopik** [thomasrepnik/idea-commit-prefix-plugin#20]
I was using this plugin with IntelliJ for some time and it was fine. After upgrade to IntelliJ 2022.3, plugin stopped to work. No errors, just the commit message is not prefixed, as if the plugin was not installed. Settings are fine, plugin is not disabled, etc.

**Comment by thomasrepnik** [comment]
Thank you for your bug report. 
Sorry for not responding so far, i must have somehow missed it. Will take a look in the next few days.

**Comment by Nopik** [comment]
Actually, I think it started to work again? I haven't had tested it too much, I think I needed it only once over past few weeks, and it worked that time. I'll close the issue for now, and reopen it if I will notice the problem again. Sorry for the confusion.
