### ISSUE TITLE
Issues/tasks with a dash in the number causes confusion 

### ISSUE THREAD

**Issue by NiklasBr** [thomasrepnik/idea-commit-prefix-plugin#21]
### Affected Application:
 - Product: PHPStorm 
 - Version 2022.3.1

### Describe the bug
Double-numbered issues such as "JIRA-123-789" are not properly detected.

### To Reproduce
1. Have a Git branch referencing a ticket number such as `bugfix/JIRA-123-789-customer-order-blank`
2. Commit

### Expected behavior

Commit message should read "JIRA-123-789 my commit message"

### Actual result
Commit messages changes to "JIRA-123 JIRA-123-789 my commit message"

**Comment by thomasrepnik** [comment]
Thank you for your bug-report.
Is my assumption correct that your Jira Project Key is something like `JIRA_123` and your Issue Number is `789`?

if this is true, then this is an edge case the plugin can hardly handle
Imagine your branch is named as `bugfix/JIRA-123-456-789-problem`:
There are multiple possiblities:
Project Key = `JIRA_123` + Issue Number = `456` + Issue Title `789 Problem`
or
Project Key = `JIRA_123_456` + Issue Number = `789` + Issue Title `Problem`

**Comment by NiklasBr** [comment]
I'm not a Java developer so unfortunately I can  not provide a PR, but I am able to differentiate these with a regular expression.

**Comment by NiklasBr** [comment]
Also, the *main* issue I think is that it replaces the commit message *after* I click commit. So...

1. have a branch `bugfix/JIRA-123-789-customer-order-blank`
2. Write a commit message "JIRA-123-789 order interface thingymajig"
3. Click on the commit button.

Then *after* clicking on the button the plugin changes the commit message even though the JIra-prefixed message matches the branch name. Shouldn't it be possible to have a check that prevents replacement if the commit message is already prefixed with something matching the branch?

**Comment by thomasrepnik** [comment]
I will close this issue, because unfortunately it is not possible to extract the different parts from the mentioned branch name. (see also my comment above where i explained the problem: https://github.com/thomasrepnik/idea-commit-prefix-plugin/issues/21#issuecomment-1404008897)
