### ISSUE TITLE
Stopped to work when use a checkout in a terminal

### ISSUE THREAD

**Issue by Yelakelly** [thomasrepnik/idea-commit-prefix-plugin#22]
### Affected Application:
 - Product: [e.g. Webstorm]
 - Version [e.g. 2022.1]

### Describe the bug
Autoprefix doesn't work if try to `git checkout -b somebranch` in a terminal or just `git checkout somebranch`, but works perfectly fine if I switch branches via Git tab.

### To Reproduce
1. Open project
2. Switch branch using `git checkout` in terminal

### Expected behavior
Autoprefix work

**Comment by thomasrepnik** [comment]
Thank you for your Bug Report. 
I just tried to reproduce the issue, but wasn't able to. 
Do you have the newest Plugin Version installed?

With IntelliJ 2023.1.1 it's working as expected:
![screencap](https://github.com/thomasrepnik/idea-commit-prefix-plugin/assets/47736416/ca54c8fc-e1dc-4e94-8743-4ce526979aab)

if i could reproduce the issue i would be glad to help you

**Comment by Yelakelly** [comment]
Yes. I had version before 1.2.1. I installed latest webstorm and updated plugin and now it works.
