### ISSUE TITLE
Support older IDEs

### ISSUE THREAD

**Issue by OndraBasler** [thomasrepnik/idea-commit-prefix-plugin#25]
I noticed that the new release 1.3.0 is supported from Android Studio — Iguana | 2023.2.1 Canary 8+ https://plugins.jetbrains.com/plugin/14238-git-auto-prefix/versions/stable/429817

I use Android Studio Giraffe | 2022.3.1 Patch 1.
Is it possible to support this version too? I want to use the position of tag feature you recently added to 1.3.0.

**Comment by thomasrepnik** [comment]
I always try to keep the plugin up to date, with the recent versions of Jetbrains products.
But it's fairly possible that this version also works with older IDE Versions. I won't backport the new feature, but you can easily build the plugin by your own. Just clone the repository, patch the plugin.xml with the IDE Support you want and try to build it. 

Maybe you have also updated your IDE in the meantime. Hope you can use the new feature as requested 🙂  thanks for using my plugin and feel free to open any issue or feature request anytime soon.
