### ISSUE TITLE
Settings form unavailable on JetBrains Rider 2023.2.2 (MacOS)

### ISSUE THREAD

**Issue by mkincyan** [thomasrepnik/idea-commit-prefix-plugin#26]
### Affected Application:
 - Product: Rider
 - Version 2023.2.2 (MacOS)

### Describe the bug
After installing the plugin for the first time, I'm expecting to see "Git Auto Prefix" in the "Tools" menu, but it is not there. The commit message is appearing however (e.g. "LIFE-123: ") however I was expecting to be able to change it to e.g. "[LIFE-123] ".

### To Reproduce
1. Install plugin
2. Open Tools menu

### Expected behavior
Can click Git Auto Prefix to view and edit the settings.

### Screenshots
![image](https://github.com/thomasrepnik/idea-commit-prefix-plugin/assets/104577067/cd93dc46-52cb-4659-82cb-3f2060dbd8bb)
![image](https://github.com/thomasrepnik/idea-commit-prefix-plugin/assets/104577067/ed5c1231-80ad-4f96-8a7c-edad9d863381)

### Additional context
In addition to the above, I have attempted restarting Rider and restarting my Mac. I also check the .idea folder for any file that looked like it was saving the settings but couldn't find them there, perhaps because I've never set them and the defaults aren't saved in the .idea space.

**Comment by thomasrepnik** [comment]
Hi
Thank you for creating the issue. 
Yes that's correct. If  you just stick with the default settings, the file in the `.idea` folder is not necessary and is therefore not existing.

I will take a look at it in the next couple of days. 

As a workaround you could try to create a file named `git-auto-prefix.xml` in the `.idea` folder. 
The content of the file should be like this:

```
<?xml version="1.0" encoding="UTF-8"?>
<project version="4">
  <component name="ch.repnik.intellij.settings.PluginConfigService">
    <option name="wrapLeft" value="[" />
    <option name="wrapRight" value="]" />
  </component>
</project>
```

This config should give you the prefixes you want (`[LIFE-123]`)

**Comment by thomasrepnik** [comment]
Oh, i just read that you opened the tools menu. 
But the settings for the plugin should be in the **settings dialog**. Have you already tried this? (i am not familiar with rider but i think the settings dialog should be pretty similar in all jetbrains products)

<img width="637" alt="Bildschirmfoto 2023-12-16 um 17 01 17" src="https://github.com/thomasrepnik/idea-commit-prefix-plugin/assets/47736416/e9d18aa7-b220-4428-893b-81386a00e69e">

**Comment by mkincyan** [comment]
I'm terribly sorry to waste your time! I was looking in the menu -> Tools as that was where other plugin options that I've used have been, but I can now see the option in the Settings -> Tools and my changes worked a treat. Thanks!

**Comment by mkincyan** [comment]
I found it a little difficult to find any documentation on the settings. Perhaps it could be added to the root README that the settings are found in the Settings -> Tools menu of your IDE or something?
