### ISSUE TITLE
Support for Linear

### ISSUE THREAD

**Issue by rfiala** [thomasrepnik/idea-commit-prefix-plugin#30]
### Affected Application:
 - Product: [IntelliJIdea]
 - Version [2024.1.4]

### Describe the bug
Not a bug actually and rather a feature request. Just switched from JIRA to Linear and Linear is using "lowercase" whenever we create a branch. 

As you can see the branch name is all lowercase:
![image](https://github.com/user-attachments/assets/2d454dba-b3cb-49c8-9e48-ad96bacb40bd)

### Expected behavior
Could you add a new option for Linear.app where you check for lowercase Issue keys? 
![image](https://github.com/user-attachments/assets/7c55f2e4-341b-45ae-9017-409801245e66)

Thinking of something simple like:
* feature/ma-1234-dwdw-121
* bug/ma-1234-ddwdw-1212

==> ***(?<=\/)([a-z0-9]+-[0-9]+)***

**Comment by thomasrepnik** [comment]
Thank you for your feature request
Will take a look at it

**Comment by thomasrepnik** [comment]
i just added support for lowerkeys. It should be working if you just use the Jira setting as before.
